apiVersion: provisioning.dpu.nvidia.com/v1alpha1
kind: DPUDiscovery
metadata:
  name: dpu-discovery
  namespace: dpf-operator-system
spec:
  ipRangeSpec:
    ipRange:
      startIP: '{{.spectro.var.dpfDiscoveryStartIP}}'
      endIP: '{{.spectro.var.dpfDiscoveryEndIP}}'